// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Neuralyzer = Neuralyzer || {};

/**
 * @const
 * @namespace
 */
Neuralyzer.Transport = Neuralyzer.Transport || {};

/**
 * @const
 * @namespace
 */
Neuralyzer.Transport.FlatBuffers = Neuralyzer.Transport.FlatBuffers || {};

/**
 * @constructor
 */
Neuralyzer.Transport.FlatBuffers.Participant = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Neuralyzer.Transport.FlatBuffers.Participant}
 */
Neuralyzer.Transport.FlatBuffers.Participant.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Neuralyzer.Transport.FlatBuffers.Participant=} obj
 * @returns {Neuralyzer.Transport.FlatBuffers.Participant}
 */
Neuralyzer.Transport.FlatBuffers.Participant.getRootAsParticipant = function(bb, obj) {
  return (obj || new Neuralyzer.Transport.FlatBuffers.Participant).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Neuralyzer.Transport.FlatBuffers.Participant.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Neuralyzer.Transport.FlatBuffers.Participant.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Neuralyzer.Transport.FlatBuffers.Participant.startParticipant = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
Neuralyzer.Transport.FlatBuffers.Participant.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
Neuralyzer.Transport.FlatBuffers.Participant.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Neuralyzer.Transport.FlatBuffers.Participant.endParticipant = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Neuralyzer.Transport.FlatBuffers.Participant.finishParticipantBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.Neuralyzer = Neuralyzer;
