// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Neuralyzer = Neuralyzer || {};

/**
 * @const
 * @namespace
 */
Neuralyzer.Transport = Neuralyzer.Transport || {};

/**
 * @const
 * @namespace
 */
Neuralyzer.Transport.FlatBuffers = Neuralyzer.Transport.FlatBuffers || {};

/**
 * @constructor
 */
Neuralyzer.Transport.FlatBuffers.Vector3 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Neuralyzer.Transport.FlatBuffers.Vector3}
 */
Neuralyzer.Transport.FlatBuffers.Vector3.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
Neuralyzer.Transport.FlatBuffers.Vector3.prototype.x = function() {
  return this.bb.readFloat32(this.bb_pos);
};

/**
 * @returns {number}
 */
Neuralyzer.Transport.FlatBuffers.Vector3.prototype.y = function() {
  return this.bb.readFloat32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
Neuralyzer.Transport.FlatBuffers.Vector3.prototype.z = function() {
  return this.bb.readFloat32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @param {number} z
 * @returns {flatbuffers.Offset}
 */
Neuralyzer.Transport.FlatBuffers.Vector3.createVector3 = function(builder, x, y, z) {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

/**
 * @constructor
 */
Neuralyzer.Transport.FlatBuffers.RoomObject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Neuralyzer.Transport.FlatBuffers.RoomObject}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Neuralyzer.Transport.FlatBuffers.RoomObject=} obj
 * @returns {Neuralyzer.Transport.FlatBuffers.RoomObject}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.getRootAsRoomObject = function(bb, obj) {
  return (obj || new Neuralyzer.Transport.FlatBuffers.RoomObject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.disposable = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : true;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.owner = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {Neuralyzer.Transport.FlatBuffers.Vector3=} obj
 * @returns {Neuralyzer.Transport.FlatBuffers.Vector3|null}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.position = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new Neuralyzer.Transport.FlatBuffers.Vector3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {Neuralyzer.Transport.FlatBuffers.Vector3=} obj
 * @returns {Neuralyzer.Transport.FlatBuffers.Vector3|null}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.lookDirection = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new Neuralyzer.Transport.FlatBuffers.Vector3).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.prefab = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.isHidden = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.startRoomObject = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} disposable
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addDisposable = function(builder, disposable) {
  builder.addFieldInt8(1, +disposable, +true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ownerOffset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addOwner = function(builder, ownerOffset) {
  builder.addFieldOffset(2, ownerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionOffset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addPosition = function(builder, positionOffset) {
  builder.addFieldStruct(3, positionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} lookDirectionOffset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addLookDirection = function(builder, lookDirectionOffset) {
  builder.addFieldStruct(4, lookDirectionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} prefabOffset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addPrefab = function(builder, prefabOffset) {
  builder.addFieldOffset(5, prefabOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isHidden
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addIsHidden = function(builder, isHidden) {
  builder.addFieldInt8(6, +isHidden, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.addName = function(builder, nameOffset) {
  builder.addFieldOffset(7, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.endRoomObject = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Neuralyzer.Transport.FlatBuffers.RoomObject.finishRoomObjectBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.Neuralyzer = Neuralyzer;
